#ValueClouds
- platform: rest
  name: "ValueClouds Inverter Raw"
  resource_template: >
    https://api.valueclouds.com/drt/api/auth/web/deviceDats?page=1&pageSize=15&devaddr=4&devcode=6422&pn=E50000220625866617&sn=DEV19CBFDDC614D25E&date={{ now().strftime('%Y-%m-%d') }}
  method: GET
  headers:
    Token: "{{ states('input_text.valueclouds_token') }}"
    project: "IOT"
    i18n: "ru_RU"
  value_template: "{{ value_json.success }}"
  json_attributes_path: "$.data.row[0]"
  json_attributes:
  - field
  scan_interval: 300 # 5 минут
